# Generated by Django 5.1.6 on 2025-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaDeEmprego',
            fields=[
                ('id_vaga', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(blank=True, max_length=70, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('info_adicionais', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_requisito', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficios', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'db_table': 'vagas_de_emprego',
            },
        ),
        migrations.DeleteModel(
            name='Vaga',
        ),
    ]
