# Generated by Django 5.1.6 on 2025-04-24 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vagadeemprego_delete_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='vagadeemprego',
            name='id_requisito',
        ),
        migrations.AddField(
            model_name='vagadeemprego',
            name='cargo',
            field=models.CharField(default='Desenvolvedor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagadeemprego',
            name='requisitos',
            field=models.ManyToManyField(related_name='vagas', to='vagas.requisito'),
        ),
        migrations.AddField(
            model_name='requisito',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='vagas.vaga'),
        ),
    ]
