# Generated by Django 5.1.6 on 2025-05-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_requisito_vaga_remove_vagadeemprego_id_requisito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='nome_empresa',
            field=models.CharField(default='empresa_desconhecida', max_length=200),
        ),
    ]
