# Generated by Django 5.1.6 on 2025-05-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_remove_vaga_nome_empresa_chat_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='vagadeemprego',
            name='requisitos',
        ),
        migrations.DeleteModel(
            name='Vaga',
        ),
        migrations.DeleteModel(
            name='Requisito',
        ),
        migrations.DeleteModel(
            name='VagaDeEmprego',
        ),
    ]
